rootProject.name = 'eleganteer-cloud'

// 基础服务模块
include ':eleganteer-authorization-server'
include ':eleganteer-gateway-server'
include ':eleganteer-register-server'
include ':eleganteer-system-server'

// Starter 模块
include ':eleganteer-common-starter'
include ':eleganteer-feign-starter'
include ':eleganteer-resource-server-starter'
include ':eleganteer-swagger-starter'

