dependencies {
    api project(':eagle-starter:eagle-common-starter')
    api project(':eagle-starter:eagle-redis-starter')
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.aspectj:aspectjweaver'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.mockito:mockito-core'
}
