dependencies {
    api project(':eagle-starter:eagle-common-starter')
    api 'org.springframework.boot:spring-boot-starter-data-elasticsearch'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.mockito:mockito-core'
}
