dependencies {
    api project(':eagle-starter:eagle-common-starter')
    api 'org.springdoc:springdoc-openapi-starter-common'
    api 'org.springframework:spring-web'
    api 'org.springframework.security:spring-security-core'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui'
    testImplementation 'org.springdoc:springdoc-openapi-starter-webflux-ui'
}
