dependencies {
    api project(':eagle-starter:eagle-common-starter')
    api 'com.baomidou:mybatis-plus-spring-boot4-starter'
    api 'jakarta.validation:jakarta.validation-api'
    runtimeOnly 'com.mysql:mysql-connector-j'
    compileOnly 'com.alibaba:druid-spring-boot-3-starter'

    // EagleMetaObjectHandler 通过 SecurityContextHolder 取审计用户
    compileOnly 'org.springframework.security:spring-security-core'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
