dependencies {
    api project(':eagle-starter:eagle-common-starter')
    api project(':eagle-starter:http-client-starter')

    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-restclient'

    compileOnly 'com.fasterxml.jackson.core:jackson-databind'
    compileOnly 'org.slf4j:slf4j-api'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind'
}

bootJar.enabled = false
jar.enabled = true
