dependencies {
    api project(':eagle-starter:eagle-common-starter')
    api project(':eagle-starter:eagle-dynamic-datasource-starter')
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-data-jpa'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}
