dependencies {
    api project(':eagle-starter:eagle-common-starter')
    // DATABASE 模式可选依赖，仅需此模式的消费方需显式引入
    compileOnly project(':eagle-starter:eagle-dynamic-datasource-starter')
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-data-jpa'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}
